#
org:
  snowjak:
    rays:
      decomposition-size: 128
      security:
        # When the UI is generated, use these form-parameter names for username and password
        username-parameter: username
        password-parameter: password
rabbitmq:
  taskq: rays.render-task
  progressq: rays.render-progress
  resultq: rays.render-result
  deleteExchange: rays.render-delete
#
# Start the embedded Web-server on port 8080
server:
  port: 8080
#
spring:
  flyway:
    locations: classpath:db/migration/{vendor}
  rabbitmq:
    host: localhost
    listener:
      simple:
        concurrency: 4
  datasource:
    url: jdbc:hsqldb:mem:rays
    hikari:
      initialization-fail-timeout: 120
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: INFO
    org.snowjak.rays: TRACE
