org:
  snowjak:
    rays:
      security:
        username-parameter: username
        password-parameter: password
      frontend:
        parallelism: 2
      backend:
        parallelism: 4
server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    listener:
      simple:
        concurrency: 2
  datasource:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
rabbitmq:
  taskq: rays.render-task
  progressq: rays.render-progress
  resultq: rays.render-result
logging:
  level:
    org.springframework.security: INFO
    org.snowjak.rays: DEBUG