create table render_setup (id bigint generated by default as identity (start with 1), version bigint not null, created timestamp, scene_id bigint, film_json varchar(1024) not null, renderer_json varchar(1024) not null, sampler_json varchar(1024) not null, camera_json varchar(1024) not null, primary key (id) );

alter table render drop constraint FK_render_scene;
alter table render_setup add constraint FK_render_setup_scene foreign key (scene_id) references scene (id);

alter table render add temp_render_setup_id bigint null;